import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ThemeProviders from "@/providers/ThemeProviders";
import AuthProvider from "@/providers/auth-provider";
import QueryProvider from "@/providers/query-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Discophiles ! Share your favorite albums</title>
        <meta
          name="description"
          content="Share your favorite albums with community of music lovers"
        />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="stylesheet" />
      </head>
      <body
        className={`${inter.className} flex flex-col flex-between min-h-screen mx-auto w-full max-w-7xl`}
      >
        <QueryProvider>
          <AuthProvider>
            <ThemeProviders
              attribute="class"
              defaultTheme="system"
              enableSystem
            >
              <Header />
              {children}
              <Footer />
            </ThemeProviders>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
